# Generated by Django 5.1.4 on 2025-04-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_grievanceticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievanceticket',
            name='is_concluded',
            field=models.BooleanField(default=False),
        ),
    ]
