# Generated by Django 5.1.4 on 2025-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_grievanceticket_is_concluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievanceticket',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
