# Generated by Django 5.1.4 on 2025-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_grievanceticket_image_grievanceticket_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grievance_image'),
        ),
    ]
