# Generated by Django 5.1.4 on 2025-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_tax_rename_parent_category_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whats_inside',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
