# Generated by Django 5.1.4 on 2025-01-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productattributecategory_productattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
