# Generated by Django 5.1.4 on 2025-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_productspecification_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.URLField(blank=True, null=True),
        ),
    ]
