# Generated by Django 5.1.4 on 2025-01-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantRelationshipAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_value', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_item', to='inventory.product')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.variantrelationshipattribute')),
            ],
        ),
    ]
