# Generated by Django 5.1.4 on 2025-01-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_variantrelationshipattribute_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_item', to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_parent', to='inventory.product'),
        ),
    ]
