# Generated by Django 5.1.4 on 2025-01-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productvariant_variant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category Will Be Unique', max_length=255, unique=True),
        ),
    ]
