# Generated by Django 5.1.4 on 2025-05-04 14:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairing_strength', models.PositiveSmallIntegerField(default=1, help_text='Rating from 1-5 indicating how strongly these products pair together', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, help_text='Optional description explaining why these products work well together', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paired_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paired_with', to='inventory.product')),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paired_products', to='inventory.product')),
            ],
            options={
                'ordering': ['-pairing_strength', '-created_at'],
                'unique_together': {('primary_product', 'paired_product')},
            },
        ),
    ]
