# Generated by Django 5.1.4 on 2025-05-04 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productpairing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('similar', 'Similar Products'), ('frequently_bought', 'Frequently Bought Together'), ('popular_in_category', 'Popular in Category'), ('trending', 'Trending Now'), ('custom', 'Custom Recommendation')], max_length=30)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='inventory.product')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='inventory.product')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['source_product', 'recommendation_type', '-score'], name='inventory_p_source__c94c04_idx')],
                'unique_together': {('source_product', 'recommended_product', 'recommendation_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user'], name='inventory_p_user_id_d777f7_idx'), models.Index(fields=['product'], name='inventory_p_product_1d51ad_idx'), models.Index(fields=['session_id'], name='inventory_p_session_a65fca_idx')],
            },
        ),
    ]
