# Generated by Django 5.0.6 on 2025-05-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_productrecommendation_productview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_name', models.CharField(help_text='eg . FPS MONGER', max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=50)),
                ('cpu_clock', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=200)),
                ('gpu_vram', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='feature_product_image')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
