# Generated by Django 5.0.6 on 2025-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_productupdate_productupdatenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productupdate',
            name='update_file',
            field=models.FileField(blank=True, null=True, upload_to='product_updates/%Y/%m/'),
        ),
    ]
