# Generated by Django 5.0.6 on 2025-05-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
