# Generated by Django 5.0.6 on 2025-05-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
