# Generated by Django 5.0.6 on 2025-06-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nvidia_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_image', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.FileField(upload_to='nvidia_image')),
                ('link', models.URLField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
