# Generated by Django 5.0.6 on 2025-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_nvidia_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nvidia_image',
            options={'verbose_name': 'Nvidia Image', 'verbose_name_plural': 'Nvidia Images'},
        ),
        migrations.AddField(
            model_name='nvidia_image',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
