# Generated by Django 5.1.4 on 2025-04-01 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_deliveryaddress'),
        ('orders', '0003_order_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='home.deliveryaddress'),
        ),
    ]
