# Generated by Django 5.1.4 on 2025-04-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_price_after_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_after_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
